# Generated by Django 4.0.5 on 2022-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=150, verbose_name='Layer')),
                ('downlink', models.CharField(max_length=150, verbose_name='Downlink')),
                ('copper_fiber', models.CharField(max_length=150, verbose_name='Copper/Fiber')),
                ('poe', models.BooleanField(verbose_name='PoE')),
                ('uplink', models.CharField(max_length=150, verbose_name='Uplink')),
                ('switching_cap', models.CharField(max_length=150, verbose_name='Switching capacity')),
                ('forwarding_rate', models.CharField(max_length=150, verbose_name='Forwarding rate')),
                ('stack', models.BooleanField(max_length=150, verbose_name='Stack')),
                ('power_supply', models.CharField(max_length=150, verbose_name='Power Supply')),
                ('advanced_cup', models.CharField(max_length=150, verbose_name='Advanced switch capabilities and scale')),
                ('network_eg', models.CharField(max_length=150, verbose_name='Network segmentation')),
                ('l3_function', models.CharField(max_length=150, verbose_name='L3 functions')),
            ],
        ),
    ]
