# Generated by Django 4.0.5 on 2022-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='model',
            field=models.CharField(default=1, max_length=150, verbose_name='Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='uplink_model',
            field=models.CharField(default=1, max_length=150, verbose_name='Uplink Model'),
            preserve_default=False,
        ),
    ]
