# Generated by Django 4.0.5 on 2022-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_switch_model_switch_uplink_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='copper_fiber2',
            field=models.CharField(default=1, max_length=150, verbose_name='Copper/Fiber2'),
            preserve_default=False,
        ),
    ]
