# Generated by Django 4.0.5 on 2022-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0004_alter_switch_advanced_cup_alter_switch_copper_fiber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='advanced_cup',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Advanced switch capabilities and scale'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='copper_fiber',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Copper/Fiber'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='copper_fiber2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Copper/Fiber2'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='downlink',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Downlink'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='forwarding_rate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Forwarding rate'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='l3_function',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='L3 functions'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='layer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Layer'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='network_eg',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Network segmentation'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='power_supply',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Power Supply'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switching_cap',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Switching capacity'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uplink',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Uplink'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uplink_model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Uplink Model'),
        ),
    ]
